### ISSUE TITLE
Error on first eval

### ISSUE THREAD

**Issue by krisc** [swannodette/lt-cljs-tutorial#52]
I'm getting an error upon evaluating that very first namespace form:

```
"Invalid behavior: :lt.plugins.clojure/eval!"
TypeError: Cannot call method 'call' of undefined
    at notify (/opt/LightTable/plugins/clojure/clojure_compiled.js:1259:24)
    at check_all (/opt/LightTable/plugins/clojure/clojure_compiled.js:1274:83)
    at run_local_server (/opt/LightTable/plugins/clojure/clojure_compiled.js:1209:110)
    at try_connect (/opt/LightTable/plugins/clojure/clojure_compiled.js:347:45)
    at lt.objs.eval.find_client (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:29877:16)
    at lt.objs.eval.get_client_BANG_ (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:29907:32)
    at Function.__BEH__eval_BANG_ (/opt/LightTable/plugins/clojure/clojure_compiled.js:412:69)
    at c (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:6236:18)
    at lt.object.raise_STAR_ (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:17890:74)
```

**Comment by neverfox** [comment]
@krisc Same. But I cannot install `lighttable` because it conflicts with `chromium-browser-bin`,  which is my main browser, so I cannot just get rid of it.

**Comment by neverfox** [comment]
Actually, it looks like `chromium` is now ahead of `chromium-browser-bin` so I got `lighttable` installed, but now I get the error described [here](https://groups.google.com/forum/#!topic/light-table-discussion/EwQxO5FNf74), seemingly because it gets installed as root. How did you get it to work?

**Comment by sitonapanotis** [comment]
@krisc thanks I had the same problem, installing the non-git version fixed it. I wonder what is wrong with the git PKGBUILD?
